export const ALL_DOCS = [
  {
    id: 1,
    type: 'DOCU',
    required: true,
    title: '개발 환경 세팅 가이드',
    dept: '개발',
    direction: '프로젝트 참여 전 환경 구성',
    category: '문서',
    date: '2026.07.06',
    views: 312,
    tags: ['Node.js', 'Git', 'IDE'],
    summary:
      '신입 개발자가 로컬 개발 환경을 처음부터 구성할 수 있도록 Node.js, Git, IDE 설치부터 프로젝트 실행까지 단계별로 안내하는 필수 문서입니다.',
    checklist: [
      'Node.js LTS 버전을 설치하고 node -v로 버전을 확인합니다.',
      'Git 초기 설정(이름, 이메일)을 완료하고 SSH 키를 등록합니다.',
      '프로젝트 클론 후 .env 파일 설정과 npm install을 완료합니다.',
    ],
  },
  {
    id: 2,
    type: 'DOCX',
    required: false,
    title: 'Git 브랜치 전략 및 PR 작성 규칙',
    dept: '개발',
    direction: '협업 규칙과 코드 관리',
    category: '가이드',
    date: '2026.07.02',
    views: 205,
    tags: ['Git', 'PR', '코드리뷰'],
    summary:
      '신입 개발자가 첫 작업을 안전하게 올릴 수 있도록 브랜치 생성, 커밋 메시지, PR 작성, 코드 리뷰 요청 방법을 정리한 문서입니다.',
    checklist: [
      '브랜치명은 feature/이름/작업내용 형식으로 작성합니다.',
      'PR에는 작업 내용, 테스트 결과, 리뷰 포인트를 반드시 남깁니다.',
      '리뷰 수정 요청은 성장 과정이므로 부담 갖지 않고 반영합니다.',
    ],
  },
  {
    id: 3,
    type: 'DOCU',
    required: false,
    title: '프로젝트 실행 오류 해결 FAQ',
    dept: '개발',
    direction: '자주 나는 에러 Top 3',
    category: 'FAQ',
    date: '2026.06.30',
    views: 178,
    tags: ['FAQ', 'Error', '디버깅'],
    summary:
      '개발 환경 세팅 및 프로젝트 실행 중 자주 발생하는 오류 3가지와 해결 방법을 빠르게 찾을 수 있도록 정리한 FAQ입니다.',
    checklist: [
      'port already in use 오류는 lsof -i :포트번호로 프로세스를 확인합니다.',
      'npm install 오류 시 node_modules 삭제 후 재설치를 시도합니다.',
      '환경 변수 오류는 .env 파일 위치와 변수명을 먼저 확인합니다.',
    ],
  },
  {
    id: 4,
    type: 'DOCX',
    required: false,
    title: 'API 명세 확인 및 테스트 방법',
    dept: '개발',
    direction: 'Swagger/Postman 사용법',
    category: '가이드',
    date: '2026.06.25',
    views: 143,
    tags: ['API', 'Swagger', 'Postman'],
    summary:
      '백엔드 API 명세를 Swagger UI에서 확인하고 Postman으로 직접 테스트하는 방법을 단계별로 안내합니다.',
    checklist: [
      'Swagger UI(localhost:8080/swagger-ui)에 접속해 API 목록을 확인합니다.',
      'Postman에서 Authorization 헤더에 JWT 토큰을 설정합니다.',
      '응답 코드 400/401/403의 의미를 숙지하고 요청을 검증합니다.',
    ],
  },
  {
    id: 5,
    type: 'PDF',
    required: true,
    title: '서버 접속 절차 및 Linux 기본 명령어',
    dept: '인프라',
    direction: '안전한 서버 접속',
    category: '문서',
    date: '2026.06.28',
    views: 289,
    tags: ['Linux', 'SSH', '서버'],
    summary:
      '사내 개발/운영 서버에 안전하게 접속하는 SSH 절차와 업무에 자주 사용하는 Linux 기본 명령어를 정리한 필수 문서입니다.',
    checklist: [
      'VPN 연결 후 ssh 계정@서버IP 명령어로 접속합니다.',
      '초기 접속 시 임시 비밀번호를 반드시 변경합니다.',
      'rm -rf 명령어는 복구 불가이므로 실행 전 경로를 꼭 확인합니다.',
    ],
  },
  {
    id: 6,
    type: 'PPTX',
    required: false,
    title: '배포 전 체크리스트와 로그 확인 방법',
    dept: '인프라',
    direction: '배포와 장애 대응',
    category: '체크리스트',
    date: '2026.06.24',
    views: 97,
    tags: ['배포', '로그', '장애대응'],
    summary:
      '운영 환경 배포 전 반드시 확인해야 할 항목과 배포 후 서버 로그를 통해 이상 징후를 빠르게 파악하는 방법을 정리했습니다.',
    checklist: [
      '배포 전 스테이징 환경에서 기능을 최종 검증합니다.',
      '배포 후 tail -f 로그 파일 경로로 실시간 로그를 모니터링합니다.',
      '에러 발생 시 즉시 인프라팀 슬랙 채널에 공유합니다.',
    ],
  },
  {
    id: 7,
    type: 'DOCX',
    required: false,
    title: '쿠버네티스 기본 운영 가이드',
    dept: '인프라',
    direction: '컨테이너 오케스트레이션',
    category: '가이드',
    date: '2026.06.18',
    views: 134,
    tags: ['Kubernetes', 'Docker', 'k8s'],
    summary:
      '사내 쿠버네티스 클러스터의 기본 구조를 이해하고 kubectl 명령어로 파드 상태를 확인하고 재시작하는 방법을 안내합니다.',
    checklist: [
      'kubectl get pods -n namespace로 파드 상태를 확인합니다.',
      '파드 로그는 kubectl logs 파드명으로 조회합니다.',
      '파드 재시작은 kubectl rollout restart deployment/이름을 사용합니다.',
    ],
  },
  {
    id: 8,
    type: 'PDF',
    required: true,
    title: '계정 보안과 권한 신청 절차',
    dept: '보안',
    direction: '계정·권한·개인정보 보호',
    category: '문서',
    date: '2026.06.20',
    views: 261,
    tags: ['보안', '계정', '권한'],
    summary:
      '사내 시스템 계정 발급 절차, 강력한 비밀번호 정책, 업무별 권한 신청 방법을 안내하는 보안 필수 문서입니다.',
    checklist: [
      '비밀번호는 8자 이상, 영문+숫자+특수문자를 혼합해 설정합니다.',
      '업무 외 시스템 권한은 보안팀에 공문으로 신청합니다.',
      '계정 공유는 절대 금지이며 위반 시 즉시 보안팀에 신고합니다.',
    ],
  },
  {
    id: 9,
    type: 'DOCU',
    required: false,
    title: 'ChatGPT / 생성형 AI 안전 사용 가이드',
    dept: '보안',
    direction: '사내 정보 유출 예방',
    category: 'FAQ',
    date: '2026.06.16',
    views: 188,
    tags: ['AI', 'ChatGPT', '정보보안'],
    summary:
      'ChatGPT 등 생성형 AI 도구 사용 시 사내 기밀 정보 유출을 방지하기 위한 금지 입력 유형과 안전한 활용 범위를 안내합니다.',
    checklist: [
      '고객 개인정보, 코드 전체, 계약서 내용은 AI에 입력하지 않습니다.',
      '내부 시스템 구조나 보안 정책을 질문에 포함하지 않습니다.',
      'AI 생성 코드는 반드시 직접 검토 후 사용합니다.',
    ],
  },
  {
    id: 10,
    type: 'DOCX',
    required: true,
    title: 'VPN 접속 방법 및 오류 해결 가이드',
    dept: '네트워크',
    direction: '사내망·VPN 접속',
    category: '가이드',
    date: '2026.06.12',
    views: 320,
    tags: ['VPN', '네트워크', '원격접속'],
    summary:
      '재택 및 외부 환경에서 사내망에 안전하게 접속하기 위한 VPN 설치·설정 방법과 자주 발생하는 접속 오류 해결책을 정리했습니다.',
    checklist: [
      'VPN 클라이언트를 IT 포털에서 다운로드하고 설치합니다.',
      '접속 오류 시 네트워크 어댑터를 재설정하고 재시도합니다.',
      '출장·재택 시 VPN 없이 내부 시스템 접속을 시도하지 않습니다.',
    ],
  },
  {
    id: 11,
    type: 'XLSX',
    required: false,
    title: '방화벽 포트 오픈 요청 템플릿',
    dept: '네트워크',
    direction: '요청 절차 표준화',
    category: '템플릿',
    date: '2026.06.08',
    views: 76,
    tags: ['방화벽', '포트', '템플릿'],
    summary:
      '신규 서비스 오픈이나 외부 연동 시 필요한 방화벽 포트 오픈을 네트워크팀에 정확하게 요청하기 위한 표준 템플릿입니다.',
    checklist: [
      '요청 목적, 출발지/목적지 IP, 포트 번호를 정확히 기재합니다.',
      '보안팀 사전 검토 후 네트워크팀에 최종 요청합니다.',
      '승인 완료 후 telnet으로 실제 통신 여부를 확인합니다.',
    ],
  },
  {
    id: 12,
    type: 'DOCU',
    required: false,
    title: '회사 소개와 협업툴 계정 설정',
    dept: '공통',
    direction: '입사 후 기본 적응',
    category: '온보딩',
    date: '2026.06.04',
    views: 155,
    tags: ['온보딩', 'Slack', 'Jira'],
    summary:
      '입사 후 첫 주에 설정해야 하는 협업 도구(Slack, Jira, Confluence) 계정 설정 방법과 팀 채널 참여 방법을 안내합니다.',
    checklist: [
      'Slack 회사 워크스페이스에 사번으로 가입하고 프로필을 설정합니다.',
      'Jira에서 소속 팀 프로젝트를 즐겨찾기에 추가합니다.',
      '팀 공통 채널 외에 관심 채널을 1개 이상 추가로 참여합니다.',
    ],
  },
];
